Update k8s_offline.yml

diff --git a/.github/workflows/k8s_offline.yml b/.github/workflows/k8s_offline.yml
--- a/.github/workflows/k8s_offline.yml
+++ b/.github/workflows/k8s_offline.yml
@@ -20,7 +20,12 @@ jobs:
         id: read_version
         run: |
           KUBE_VERSION=$(awk -F': ' '/kubernetes_version:/ {print $2}' deploy/pipeline/kubeversion.yaml | tr -d '[:space:]')
+          if [[ -z "$KUBE_VERSION" ]]; then
+            echo "Error: Kubernetes version is missing from kubeversion.yaml!"
+            exit 1
+          fi
           echo "kube_version=$KUBE_VERSION" >> $GITHUB_ENV
+
 
   build:
     name: "Build Offline Installer for ${{ matrix.os }}"
